=== G48R1/CUSB-App-project/validation/schemas/canto-singolo.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "canto",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": ["canto"]
    },
    "id": {
      "type": "integer",
      "minimum": 1
    },
    "info": {
      "type": "object",
      "properties": {
        "tonalita": {
          "$ref": "tonalita.schema.json"
        },
        "metro": {
          "type": "string"
        },
        "tempo": {
          "type": "object",
          "properties": {
            "velocita": {
              "type": "string",
              "oneOf": [
                {"enum": ["veloce", "medio", "lento"]},
                {"enum": ["lentissimo", "adagio", "andante", "allegro", "presto", "prestissimo"]}
              ]
            },
            "bpm": {
              "type": "number",
              "minimum": 1
            }
          },
          "required": ["velocita"],
          "additionalProperties": false
        }
      },
      "required": ["tonalita"],
      "additionalProperties": false
    },
    "titolo": {
      "type": "string",
      "minLength": 1
    },
    "intro": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "contenuto": {
            "$ref": "strumentale.schema.json"
          }
        },
        "required": ["contenuto"],
        "additionalProperties": false
      }
    },
    "outro": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "contenuto": {
            "$ref": "strumentale.schema.json"
          }
        },
        "required": ["contenuto"],
        "additionalProperties": false
      }
    },
    "strofe": {
      "type": "array",
      "items": {
        "$ref": "stanza.schema.json"
      }
    },
    "pre-chorus": {
      "type": "array",
      "items": {
        "$ref": "stanza.schema.json"
      }
    },
    "bridge": {
      "type": "array",
      "items": {
        "$ref": "stanza.schema.json"
      }
    },
    "ritornelli": {
      "type": "array",
      "items": {
        "$ref": "stanza.schema.json"
      }
    },
    "strumentali": {
      "type": "array",
      "items": {
        "$ref": "strumentale.schema.json"
      }
    },
    "struttura": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "struttura": {
            "$ref": "struttura-canto.schema.json"
          }
        },
        "required": ["label", "struttura"],
        "additionalProperties": false
      }
    }
  },
  "required": ["type", "id", "titolo", "info"],
  "additionalProperties": false
}

=== G48R1/CUSB-App-project/Libretto/canti/OGGI TI CHIAMO/oggi-ti-chiamo.json
{
  "type": "canto",
  "id": 1,
  "titolo": "OGGI TI CHIAMO",
  "info": {
    "tonalita": {
      "type": "tonalita",
      "tono": "DO",
      "modo": "M"
    }
  },
  "intro": [
    {
      "label": "0",
      "contenuto": {
        "type": "strumentale",
        "contenuto": {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "DO"
            },
            {
              "type": "accordo",
              "base": "SIb"
            },
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 2
            },
            {
              "sep": " ",
              "qta": 2
            },
            {
              "sep": " ",
              "qta": 2
            }
          ]
        }
      }
    }
  ],
  "outro": [
    {
      "label": "0",
      "contenuto": {
        "type": "strumentale",
        "contenuto": {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "DO"
            },
            {
              "type": "accordo",
              "base": "SIb"
            },
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 2
            },
            {
              "sep": " ",
              "qta": 2
            },
            {
              "sep": " ",
              "qta": 2
            }
          ]
        }
      }
    }
  ],
  "strofe": [
    {
      "type": "strofa",
      "id": 1,
      "righe_accordi": [
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "DO"
            },
            {
              "type": "accordo",
              "base": "SIb"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 18
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 14
            },
            {
              "sep": " ",
              "qta": 19
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "DO"
            },
            {
              "type": "accordo",
              "base": "SIb"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 25
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 11
            },
            {
              "sep": " ",
              "qta": 12
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "LA",
              "extra": {
                "alterazione": "-"
              }
            },
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "SOL"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 13
            },
            {
              "sep": " ",
              "qta": 7
            },
            {
              "sep": " ",
              "qta": 13
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "LA",
              "extra": {
                "alterazione": "-"
              }
            },
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "SOL"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 4
            },
            {
              "sep": " ",
              "qta": 14
            },
            {
              "sep": " ",
              "qta": 8
            }
          ]
        }
      ],
      "righe_testo": [
        {
          "type": "riga-testo",
          "contenuto": [
            {
              "type": "testo",
              "testo": " Oggi ti chiamo alla vita"
            }
          ]
        },
        {
          "type": "riga-testo",
          "contenuto": [
            {
              "type": "testo",
              "testo": " t'invito a seguirmi, a venire con Me."
            }
          ]
        },
        {
          "type": "riga-testo",
          "contenuto": [
            {
              "type": "testo",
              "testo": " Apri i tuoi occhi e il tuo cuore"
            }
          ]
        },
        {
          "type": "riga-testo",
          "contenuto": [
            {
              "type": "testo",
              "testo": " dimentica tutto e segui Me."
            }
          ]
        },
        {
          "type": "riga-testo",
          "contenuto": [
            {
              "type": "testo",
              "testo": " Non avere pi√π paura di lasciare quel che hai,"
            }
          ]
        },
        {
          "type": "riga-testo",
          "contenuto": [
            {
              "type": "testo",
              "testo": " il senso vero della vita troverai."
            }
          ]
        }
      ],
      "schema": {
        "type": "struttura-stanza",
        "schema": [
          {
            "componente": "accordi",
            "posizione": 0
          },
          {
            "componente": "testo",
            "posizione": 0
          },
          {
            "componente": "accordi",
            "posizione": 1
          },
          {
            "componente": "testo",
            "posizione": 1
          },
          {
            "componente": "accordi",
            "posizione": 2
          },
          {
            "componente": "testo",
            "posizione": 2
          },
          {
            "componente": "accordi",
            "posizione": 3
          },
          {
            "componente": "testo",
            "posizione": 3
          },
          {
            "componente": "accordi",
            "posizione": 4
          },
          {
            "componente": "testo",
            "posizione": 4
          },
          {
            "componente": "accordi",
            "posizione": 5
          },
          {
            "componente": "testo",
            "posizione": 5
          }
        ]
      }
    },
    {
      "type": "strofa",
      "id": 3,
      "righe_accordi": [
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "DO"
            },
            {
              "type": "accordo",
              "base": "SIb"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 18
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 14
            },
            {
              "sep": " ",
              "qta": 18
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "DO"
            },
            {
              "type": "accordo",
              "base": "SIb"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 1
            },
            {
              "sep": " ",
              "qta": 16
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "FA"
            },
            {
              "type": "accordo",
              "base": "DO"
            }
          ],
          "spazi": [
            {
              "sep": " ",
              "qta": 14
            },
            {
              "sep": " ",
              "qta": 15
            }
          ]
        },
        {
          "type": "riga-accordi",
          "contenuto": [
            {
              "type": "accordo",
              "base": "LA",
