=== G48R1/CUSB-App-project/validation/schemas/stanza-unico.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "stanza-unico.schema.json",
  "title": "stanza",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": ["strofa", "ritornello", "pre-chorus", "bridge"]
    },
    "id": {
      "type": "number",
      "minimum": 0
    },
    "righe_accordi": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["riga-accordi"]
          },
          "contenuto": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["accordo"]
                    },
                    "base": {
                      "type": "string",
                      "enum": ["DO", "DO#", "REb", "RE", "RE#", "MIb", "MI", "FA", "FA#", "SOLb", "SOL", "SOL#", "LAb", "LA", "LA#", "SIb", "SI"]
                    },
                    "extra": {
                      "type": "object",
                      "properties": {
                        "alterazione": {
                          "type": "string"
                        },
                        "slash": {
                          "type": "object",
                          "properties": {
                            "basso": {
                              "type": "string",
                              "enum": ["DO", "DO#", "REb", "RE", "RE#", "MIb", "MI", "FA", "FA#", "SOLb", "SOL", "SOL#", "LAb", "LA", "LA#", "SIb", "SI"]
                            },
                            "extra": {
                              "type": "number"
                            }
                          }
                        }
                      }
                    }
                  },
                  "required": ["type", "base"],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["commento"]
                    },
                    "contenuto": {
                        "type": "string"
                    },
                    "sep_ext_sx": {
                        "type": "string"
                    },
                    "sep_ext_dx": {
                        "type": "string"
                    }
                  },
                  "required": ["type", "contenuto"],
                  "additionalProperties": false
                }
              ]
            }
          },
          "spazi": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "sep": {
                  "type": "string",
                  "enum": [" ", "_", "‚èù"]
                },
                "qta": {
                  "type": "number"
                }
              },
              "required": ["sep", "qta"],
              "additionalProperties": false
            }
          }
        },
        "required": ["type", "contenuto", "spazi"],
        "additionalProperties": false
      }
    },
    "righe_testo": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["riga-voce", "riga-testo", "stanza-breve"]
          },
          "contenuto": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "enum": ["testo"]
                    },
                    "testo": {
                      "type": "string"
                    }
                  },
                  "required": ["type", "testo"],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["commento"]
                    },
                    "contenuto": {
                        "type": "string"
                    },
                    "sep_ext_sx": {
                        "type": "string"
                    },
                    "sep_ext_dx": {
                        "type": "string"
                    }
                  },
                  "required": ["type", "contenuto"],
                  "additionalProperties": false
                }
              ]
            }
          },
          "commento": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["commento"]
              },
              "contenuto": {
                  "type": "string"
              },
              "sep_ext_sx": {
                  "type": "string"
              },
              "sep_ext_dx": {
                  "type": "string"
              }
            },
            "required": ["type", "contenuto"],
            "additionalProperties": false
          }
        },
        "required": ["type", "contenuto"],
        "additionalProperties": false
      }
    },
    "assegnata": {
      "type": "string",
      "enum": ["maschi", "femmine", "tutti", "solista", "solista-m1", "solista-m2","solista-f1", "solista-f2", "gruppo-1", "gruppo-2", "gruppo-3"]
    },
    "righe_assegnate": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ref_riga": {
            "type": "number"
          },
          "assegnata": {
            "type": "string",
            "enum": ["maschi", "femmine", "tutti", "solista", "solista-m1", "solista-m2","solista-f1", "solista-f2", "gruppo-1", "gruppo-2", "gruppo-3"]
          }
        },
        "required": ["ref_riga", "assegnata"],
        "additionalProperties": false
      }
    },
    "seconde_voci": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["voce"]
          },
          "registro": {
            "type": "string",
            "enum": ["soprani", "contralti", "tenori", "bassi", "alti", "medi"]
          },
          "voce": {
            "type": "string",
            "enum": ["terza", "quinta", "~terza", "~quinta", "mista"]
          },
          "assegnata": {
            "type": "string",
            "enum": ["maschi", "femmine", "tutti", "solista"]
          },
          "righe_testo": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ref_riga": {
                  "type": "integer",
                  "minimum": 0
                },
                "testo": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["riga-voce", "riga-testo", "stanza-breve"]
                    },
                    "contenuto": {
                      "type": "array",
                      "items": {
                        "oneOf": [
                          {
                            "type": "object",
                            "properties": {
                              "type": {
                                "enum": ["testo"]
                              },
                              "testo": {
                                "type": "string"
                              }
                            },
                            "required": ["type", "testo"],
                            "additionalProperties": false
                          },
                          {
                            "type": "object",
                            "properties": {
                              "type": {
                                "type": "string",
                                "enum": ["commento"]
                              },
                              "contenuto": {
                                  "type": "string"
                              },
                              "sep_ext_sx": {
                                  "type": "string"
                              },
                              "sep_ext_dx": {
                                  "type": "string"
                              }
                            },
                            "required": ["type", "contenuto"],
                            "additionalProperties": false
                          }
                        ]
                      }
                    },
                    "commento": {
                      "type": "object",
                      "properties": {
                        "type": {
                          "type": "string",
                          "enum": ["commento"]
                        },
                        "contenuto": {
                            "type": "string"
                        },
                        "sep_ext_sx": {
                            "type": "string"
                        },
                        "sep_ext_dx": {
                            "type": "string"
                        }
                      },
                      "required": ["type", "contenuto"],
                      "additionalProperties": false
                    }
                  },
                  "required": ["type", "contenuto"],
                  "additionalProperties": false
                }
              },
              "required": ["ref_riga", "testo"],
              "additionalProperties": false
            }
          },
          "pentagramma": {
            "type": "string"
          }
        },
        "required": ["type", "registro", "righe_testo"],
        "additionalProperties": false
      }
    },
    "moltiplicatore": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["moltiplicatore"]
        },
        "moltiplicatore": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["commento"]
            },
            "contenuto": {
                "type": "string"
            },
            "sep_ext_sx": {
                "type": "string"
            },
            "sep_ext_dx": {
                "type": "string"
            }
          },
          "required": ["type", "contenuto"],
          "additionalProperties": false
        },
        "start": {
          "type": "number"
        },
        "end": {
          "type": "number"
        }
      },
      "required": ["type", "moltiplicatore", "start", "end"],
      "additionalProperties": false
    },
    "breve": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["riga-voce", "riga-testo", "stanza-breve"]
        },
        "contenuto": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "enum": ["testo"]
                  },
                  "testo": {
                    "type": "string"
                  }
                },
                "required": ["type", "testo"],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": ["commento"]
                  },
                  "contenuto": {
                      "type": "string"
                  },
                  "sep_ext_sx": {
                      "type": "string"
                  },
                  "sep_ext_dx": {
                      "type": "string"
                  }
                },
                "required": ["type", "contenuto"],
                "additionalProperties": false
              }
            ]
          }
        },
        "commento": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["commento"]
            },
            "contenuto": {
                "type": "string"
            },
            "sep_ext_sx": {
                "type": "string"
            },
            "sep_ext_dx": {
                "type": "string"
            }
          },
          "required": ["type", "contenuto"],
          "additionalProperties": false
        }
      },
      "required": ["type", "contenuto"],
      "additionalProperties": false
    },
    "schema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["struttura-stanza"]
        },
        "schema": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "componente": {
                "type": "string",
                "enum": ["testo", "accordi"]
              },
              "posizione": {
                "type": "number"
              }
            },
            "required": ["componente", "posizione"],
            "additionalProperties": false
          }
        }
      },
      "required": ["type", "schema"],
      "additionalProperties": false
    }
  },
  "required": ["type" ,"id", "righe_testo", "schema"],
  "additionalProperties": false
}

=== G48R1/CUSB-App-project/Libretto/canti/Esempio/strofa.json
{
  "type": "strofa",
  "id": 1,
  "righe_accordi": [
    {
      "type": "riga-accordi",
      "contenuto": [
        {
          "type": "accordo",
          "base": "DO#",
          "extra": {
            "alterazione": "m7",
            "slash": {
              "basso": "SOL",
              "extra": 5
            }
          }
        },
        {
          "type": "accordo",
          "base": "DO#",
          "extra": {
            "alterazione": "m7",
            "slash": {
              "basso": "SOL",
              "extra": 5
            }
          }
        },
        {
          "type": "commento",
          "contenuto": "strofa",
          "sep_ext_sx": "(",
          "sep_ext_dx": ")"
        }
      ],
      "spazi": [
        {
          "sep": " ",
          "qta": 4
        },
        {
          "sep": " ",
          "qta": 2
        },
        {
          "sep": " ",
          "qta": 3
        }
      ]
    },
    {
      "type": "riga-accordi",
      "contenuto": [
        {
          "type": "accordo",
          "base": "DO#",
          "extra": {
            "alterazione": "m7",
            "slash": {
              "basso": "SOL",
              "extra": 5
            }
          }
        },
        {
          "type": "accordo",
          "base": "DO#",
          "extra": {
            "alterazione": "m7",
            "slash": {
              "basso": "SOL",
              "extra": 5
            }
          }
        }
      ],
      "spazi": [
        {
          "sep": " ",
          "qta": 4
        },
        {
          "sep": "‚èù",
          "qta": 1
        }
      ]
    }
  ],
  "righe_testo": [
    {
      "type": "riga-testo",
      "contenuto": [
        {
          "type": "testo",
          "testo": "lorem ipsum dolor "
        }
      ],
      "commento": {
        "type": "commento",
        "contenuto": "testo commento",
        "sep_ext_sx": "(",
        "sep_ext_dx": ")"
      }
    },
    {
      "type": "riga-testo",
      "contenuto": [
        {
          "type": "testo",
          "testo": "lorem ipsum"
        }
      ]
    },
    {
      "type": "riga-testo",
      "contenuto": [
        {
          "type": "testo",
          "testo": "lorem ipsum testo"
        }
      ]
    }
  ],
  "assegnata": "tutti",
  "seconde_voci": [
    {
      "type": "voce",
      "registro": "soprani",
      "voce": "terza",
      "assegnata": "femmine",
      "righe_testo": [
        {
          "ref_riga": 0,
          "testo": {
            "type": "riga-voce",
            "contenuto": [
              {
                "type": "testo",
                "testo":"soprani 1"
              }
            ]
          }
        },
        {
          "ref_riga": 1,
          "testo": {
            "type": "riga-voce",
            "contenuto": [
              {
                "type": "testo",
                "testo":"soprani 2"
              }
            ],
            "commento": {
              "type": "commento",
              "contenuto": "commento",
              "sep_ext_sx": "(",
              "sep_ext_dx": ")"
            }
          }
        }
      ]
    },
    {
      "type": "voce",
      "registro": "tenori",
      "voce": "~quinta",
      "assegnata": "maschi",
      "righe_testo": [
        {
          "ref_riga": 0,
          "testo": {
            "type": "riga-voce",
            "contenuto": [
              {
                "type": "testo",
                "testo":"tenori 1"
              }
            ]
          }
        },
        {
          "ref_riga": 2,
          "testo": {
            "type": "riga-voce",
            "contenuto": [
              {
                "type": "testo",
                "testo":"tenori 2"
              }
            ],
            "commento": {
              "type": "commento",
              "contenuto": "testo",
              "sep_ext_sx": "(",
              "sep_ext_dx": ")"
            }
          }
        }
      ]
    }
  ],
  "breve": {
    "type": "stanza-breve",
    "contenuto": [
      {
        "type": "testo",
        "testo": "lorem"
      }
    ],
    "commento": {
      "type": "commento",
      "contenuto": "testo commento",
      "sep_ext_sx": "(",
      "sep_ext_dx": ")"
    }
  },
  "schema": {
    "type": "struttura-stanza",
    "schema": [
      {
        "componente": "accordi",
        "posizione": 0
      },
      {
        "componente": "testo",
        "posizione": 0
      },
      {
        "componente": "accordi",
        "posizione": 1
      },
      {
        "componente": "testo",
        "posizione": 1
      },
      {
        "componente": "testo",
        "posizione": 2
      }
    ]
  }
}
