=== G48R1/CUSB-App-project/validation/schemas/strumentale.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "strumentale",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": ["strumentale"]
    },
    "label": {
      "type": "string"
    },
    "contenuto": {
      "$ref": "riga-accordi.schema.json"
    },
    "moltiplicatore": {
      "$ref": "commento.schema.json"
    }
  },
  "required": ["type", "contenuto"],
  "additionalProperties": false
}

=== G48R1/CUSB-App-project/Libretto/canti/Esempio/strumentale.json
{
  "type": "strumentale",
  "label": "intro",
  "contenuto": {
    "type": "riga-accordi",
    "contenuto": [
      {
        "type": "accordo",
        "base": "DO#",
        "extra": {
          "alterazione": "m"
        }
      },
      {
        "type": "accordo",
        "base": "DO"
      },
      {
        "type": "commento",
        "contenuto": "commento",
        "sep_ext_sx": "(",
        "sep_ext_dx": ")"
      }
    ],
    "spazi": [
      {
        "sep": " ",
        "qta": 4
      },
      {
        "sep": "‚èù",
        "qta": 1
      },
      {
        "sep": " ",
        "qta": 3
      }
    ]
  },
  "moltiplicatore": {
    "type": "commento",
    "contenuto": "x2",
    "sep_ext_sx": "(",
    "sep_ext_dx": ")"
  }
}
