=== G48R1/CUSB-App-project/validation/schemas/voce-unico.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "voce-unico.schema.json",
  "title": "voce",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "enum": ["voce"]
    },
    "registro": {
      "type": "string",
      "enum": ["soprani", "contralti", "tenori", "bassi", "alti", "medi"]
    },
    "voce": {
      "type": "string",
      "enum": ["terza", "quinta", "~terza", "~quinta", "mista"]
    },
    "assegnata": {
      "type": "string",
      "enum": ["maschi", "femmine", "tutti", "solista", "solista-m1", "solista-m2","solista-f1", "solista-f2", "gruppo-1", "gruppo-2", "gruppo-3"]
    },
    "righe_testo": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ref_riga": {
            "type": "integer",
            "minimum": 0
          },
          "testo": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["riga-voce", "riga-testo", "stanza-breve"]
              },
              "contenuto": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "type": "object",
                      "properties": {
                        "type": {
                          "enum": ["testo"]
                        },
                        "testo": {
                          "type": "string"
                        }
                      },
                      "required": ["type", "testo"],
                      "additionalProperties": false
                    },
                    {
                      "type": "object",
                      "properties": {
                        "type": {
                          "type": "string",
                          "enum": ["commento"]
                        },
                        "contenuto": {
                            "type": "string"
                        },
                        "sep_ext_sx": {
                            "type": "string"
                        },
                        "sep_ext_dx": {
                            "type": "string"
                        }
                      },
                      "required": ["type", "contenuto"],
                      "additionalProperties": false
                    }
                  ]
                }
              },
              "commento": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": ["commento"]
                  },
                  "contenuto": {
                      "type": "string"
                  },
                  "sep_ext_sx": {
                      "type": "string"
                  },
                  "sep_ext_dx": {
                      "type": "string"
                  }
                },
                "required": ["type", "contenuto"],
                "additionalProperties": false
              }
            },
            "required": ["type", "contenuto"],
            "additionalProperties": false
          }
        },
        "required": ["ref_riga", "testo"],
        "additionalProperties": false
      }
    },
    "pentagramma": {
      "type": "string"
    }
  },
  "required": ["type", "registro", "righe_testo"],
  "additionalProperties": false
}

=== G48R1/CUSB-App-project/Libretto/canti/Esempio/voce.json
{
  "type": "voce",
  "registro": "soprani",
  "voce": "terza",
  "assegnata": "maschi",
  "righe_testo": [
    {
      "ref_riga": 0,
      "testo": {
        "type": "riga-voce",
        "contenuto": [
          {
            "type": "testo",
            "testo":"lorem ipsum dolor"
          }
        ]
      }
    },
    {
      "ref_riga": 1,
      "testo": {
        "type": "riga-voce",
        "contenuto": [
          {
            "type": "testo",
            "testo":"lorem ipsum "
          }
        ],
        "commento": {
          "type": "commento",
          "contenuto": "testo commento",
          "sep_ext_sx": "(",
          "sep_ext_dx": ")"
        }
      }
    }
  ]
}
